language: python
python:
    - "3.4.2"
branches:
    only:
        - develop
        - master

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
    - pip install ply
    - pip install networkx
    - pip install pillow
script:
    - python ./tests/Analysis_test.py
    - python ./tests/DrawGraphics_test.py
    - python ./zamza/main.py ./tests/testsource.zamza 300,400 100,200
